use std::fs;
use std::path::Path;

/// JSON Schema for `llmwiki-cli`'s config file (`Config` and its sub-configs).
/// Auto-generated by `build.rs` from the `Config`/`NimConfig`/`WikiConfig`/
/// `RetryConfig` struct duplicates below. The real `Config` struct lives
/// in `src/core/config.rs`; the build.rs duplicates are kept in sync via
/// the `config_schema_has_canonical_keys` drift test in
/// `tests/doctor_test.rs` (v0.3.24+).
#[derive(schemars::JsonSchema)]
#[allow(dead_code)] // fields are consumed by schemars::schema_for!, not by Rust code
struct Config {
    #[schemars(description = "NIM API client configuration")]
    nim: NimConfig,
    #[schemars(description = "Wiki page chunking and lint settings")]
    wiki: WikiConfig,
    #[schemars(description = "Schema version of this config")]
    config_version: u32,
}

#[derive(schemars::JsonSchema)]
#[allow(dead_code)] // fields are consumed by schemars::schema_for!, not by Rust code
struct NimConfig {
    #[schemars(description = "NIM API base URL (no /v1 suffix)")]
    base_url: String,
    #[schemars(
        description = "Embedding model identifier (must be in the whitelisted NVIDIA NIM set)"
    )]
    embed_model: String,
    #[schemars(description = "Re-ranking model identifier (empty = disabled)")]
    rerank_model: String,
    #[schemars(description = "Override embedding dimension (empty = use model default)")]
    embed_dim_override: Option<usize>,
    #[schemars(description = "Env var name holding the NIM API key")]
    api_key_env: String,
    #[schemars(description = "Embedding request batch size (1+)")]
    batch_size: usize,
    #[schemars(description = "NIM request timeout in seconds")]
    request_timeout_secs: u64,
    #[schemars(description = "Retry policy for failed NIM calls")]
    retry: RetryConfig,
}

#[derive(schemars::JsonSchema)]
#[allow(dead_code)] // fields are consumed by schemars::schema_for!, not by Rust code
struct RetryConfig {
    #[schemars(description = "Maximum attempts per NIM call")]
    max_attempts: u32,
    #[schemars(description = "Backoff between retries in milliseconds")]
    backoff_ms: u64,
}

#[derive(schemars::JsonSchema)]
#[allow(dead_code)] // fields are consumed by schemars::schema_for!, not by Rust code
struct WikiConfig {
    #[schemars(description = "Default chunk size in tokens")]
    default_chunk_tokens: usize,
    #[schemars(description = "Chunk overlap in tokens (must be < default_chunk_tokens)")]
    chunk_overlap_tokens: usize,
    #[schemars(description = "Minimum chunk size in tokens (must be <= default_chunk_tokens)")]
    min_chunk_tokens: usize,
    #[schemars(description = "Require YAML frontmatter on every page")]
    require_frontmatter: bool,
    #[schemars(description = "Minimum wikilink count per page (0 = no minimum)")]
    require_wikilinks_min: usize,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=marketplace/skills/wiki/SKILL.md");
    println!("cargo:rerun-if-changed=marketplace/skills/wiki/SETUP/SKILL.md");
    println!("cargo:rerun-if-changed=marketplace/skills/wiki/LSP/SKILL.md");
    println!("cargo:rerun-if-changed=marketplace/skills/wiki/MCP/SKILL.md");
    println!("cargo:rerun-if-changed=src/core/config.rs");
    println!("cargo:rerun-if-changed=src/cli/doctor.rs");

    let manifest_dir = std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let manifest_path = Path::new(&manifest_dir);

    // Generate the hub SKILL.md stub from marketplace/skills/wiki/SKILL.md
    let hub_src = manifest_path.join("marketplace/skills/wiki/SKILL.md");
    if let Ok(content) = fs::read_to_string(&hub_src) {
        let out_path = manifest_path.join("agents/skills/wiki/SKILL.md");
        if let Some(parent) = out_path.parent() {
            if let Err(e) = fs::create_dir_all(parent) {
                println!("cargo:warning=failed to create skill dir {parent:?}: {e}");
            }
        }
        if let Err(e) = fs::write(&out_path, content) {
            println!("cargo:warning=failed to write hub SKILL.md {out_path:?}: {e}");
        }
    }

    // Write the JSON Schema for the Config type to SETUP/references/schema.json
    // so it ships with the skill bundle and can be referenced by agents.
    let schema_path = manifest_path.join("marketplace/skills/wiki/SETUP/references/schema.json");
    if let Some(parent) = schema_path.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            println!("cargo:warning=failed to create schema dir {parent:?}: {e}");
        }
    }
    let schema = schemars::schema_for!(Config);
    let schema_json = serde_json::to_string_pretty(&schema).expect("schema is always serializable");
    if let Err(e) = fs::write(&schema_path, format!("{schema_json}\n")) {
        println!("cargo:warning=failed to write schema.json {schema_path:?}: {e}");
    }

    // Write the JSON Schema for the DoctorReport type (output of
    // `wiki doctor --json`) to MCP/references/doctor.schema.json. The
    // schema is auto-generated from the `DoctorReport` struct below
    // (kept in sync with `src/cli/doctor.rs::DoctorReport` — when
    // either changes, the build will regenerate this file).
    let doctor_schema_path =
        manifest_path.join("marketplace/skills/wiki/MCP/references/doctor.schema.json");
    if let Some(parent) = doctor_schema_path.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            println!("cargo:warning=failed to create doctor schema dir {parent:?}: {e}");
        }
    }
    let doctor_schema = schemars::schema_for!(DoctorReport);
    // schemars reads `#[serde(deny_unknown_fields)]` on DoctorReport and
    // emits `"additionalProperties": false` at the root natively, so no
    // post-processing is needed.
    let doctor_schema_json =
        serde_json::to_string_pretty(&doctor_schema).expect("doctor schema is always serializable");
    // POSIX-text-file convention: end with a trailing newline. Many
    // editors (Vim with `:set fixendofile`, GitHub's web diff view)
    // expect one. v0.3.23 polish.
    if let Err(e) = fs::write(&doctor_schema_path, format!("{doctor_schema_json}\n")) {
        println!("cargo:warning=failed to write doctor.schema.json {doctor_schema_path:?}: {e}");
    }
}

#[derive(schemars::JsonSchema)]
#[allow(dead_code)] // consumed by schemars::schema_for!, not by Rust code
#[serde(deny_unknown_fields)] // → schema root `additionalProperties: false`
/// JSON Schema for the output of `wiki doctor --json`. Auto-generated
/// from the `DoctorReport` struct below (kept in sync with
/// `src/cli/doctor.rs::DoctorReport` via the
/// `doctor_json_output_validates_against_schema` drift test in
/// `tests/doctor_test.rs`).
///
/// **Breaking v0.3.17**: `active_alias` is `string | null` (was `""`
/// sentinel pre-v0.3.17). v0.3.23: `nim_status` is bounded to HTTP
/// range [100, 599] (was the full uint16 range). v0.3.22: the
/// `config` field is a reflective dotted-key → value map (same
/// shape as `wiki config show-effective`); `config_sources` is the
/// per-key source attribution (dotted-key → file-it-came-from).
struct DoctorReport {
    /// Resolved workspace directory (canonical absolute path).
    workspace: String,
    /// Active wiki-root.toml alias for this workspace, if any is registered. `None`
    /// means no alias resolves to this workspace. v0.3.17+: was `""` sentinel pre-v0.3.17.
    active_alias: Option<String>,
    /// Path to the resolved `wiki-root.toml`, or empty string if no registry entry matched.
    wiki_root_path: String,
    /// Count of entries in the discovered wiki-root.toml registry (0 if no registry).
    registry_entries: usize,
    /// Whether the per-workspace / per-computer config was loaded successfully.
    config_loaded: bool,
    /// Resolved NIM embedding model name from the merged effective config.
    embed_model: String,
    /// Resolved NIM base URL (host only, no `/v1` segment).
    nim_base_url: String,
    /// Resolved NIM API key length in bytes. 0 if the key env var is unset/empty.
    api_key_length: usize,
    /// Name of the env var that holds the NIM API key.
    api_key_env: String,
    /// Whether `GET {nim_base_url}/v1/models` returned 2xx during this run.
    nim_reachable: bool,
    /// HTTP status from the NIM probe, or `None` on network error. v0.3.23+:
    /// bounded to HTTP range [100, 599] (was the u16 range [0, 65535] before).
    #[schemars(range(min = 100, max = 599))]
    nim_status: Option<u16>,
    /// Human-readable error string from the NIM probe, or `None` on success.
    nim_error: Option<String>,
    /// Whether the resolved `embed_model` appears in the live NIM `/v1/models` response.
    embed_model_available: bool,
    /// Reflective dump of the resolved effective config as dotted-key → value pairs.
    #[schemars(
        description = "dotted-key to value map (same shape as `wiki config show-effective`)"
    )]
    config: std::collections::BTreeMap<String, String>,
    /// Per-key source attribution: dotted-key → file-it-came-from (`<default>` for built-in defaults).
    #[schemars(description = "dotted-key to source file path map (v0.3.12+)")]
    config_sources: std::collections::BTreeMap<String, String>,
}
