/// JSON Schema for `llmwiki-cli`'s config file (`Config` and its sub-configs).
/// Auto-generated by `build.rs` from the structs in this file (included via
/// `include!` from `src/core/config.rs` and from `build.rs`). This file is
/// the single source of truth — do NOT duplicate these structs or their
/// `default_*` helpers in `build.rs`.
///
/// Type imports are intentionally written as full paths on the derive
/// attributes (`schemars::JsonSchema`, `serde::Serialize`, etc.) so this
/// file does not need any `use` statements. This keeps the file
/// self-contained in any include! scope without introducing duplicate
/// `JsonSchema` name collisions when build.rs includes both
/// `config_types.rs` and `doctor_report.rs`.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct Config {
    #[serde(default = "default_nim")]
    pub nim: NimConfig,
    #[serde(default = "default_wiki")]
    pub wiki: WikiConfig,
    #[serde(default)]
    pub config_version: u32,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct NimConfig {
    #[serde(default = "default_nim_base_url")]
    pub base_url: String,
    #[serde(default = "default_embed_model")]
    pub embed_model: String,
    #[serde(default)]
    pub rerank_model: String,
    #[serde(default)]
    pub embed_dim_override: Option<usize>,
    #[serde(default = "default_api_key_env")]
    pub api_key_env: String,
    #[serde(default = "default_batch_size")]
    pub batch_size: usize,
    #[serde(default = "default_timeout")]
    pub request_timeout_secs: u64,
    #[serde(default)]
    pub retry: RetryConfig,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, Default, schemars::JsonSchema)]
pub struct RetryConfig {
    #[serde(default = "default_max_attempts")]
    pub max_attempts: u32,
    #[serde(default = "default_backoff")]
    pub backoff_ms: u64,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize, schemars::JsonSchema)]
pub struct WikiConfig {
    #[serde(default = "default_chunk_tokens")]
    pub default_chunk_tokens: usize,
    #[serde(default = "default_chunk_overlap")]
    pub chunk_overlap_tokens: usize,
    #[serde(default = "default_min_chunk")]
    pub min_chunk_tokens: usize,
    #[serde(default = "default_true")]
    pub require_frontmatter: bool,
    #[serde(default = "default_wikilinks_min")]
    pub require_wikilinks_min: usize,
}

// ─── Default value helpers ────────────────────────────────────────────
//
// These functions are referenced by the `#[serde(default = "...")]`
// attributes above AND called by schemars 1.0 during schema generation
// to populate the JSON Schema's `default` keyword entries.
//
// Defined here (not in `src/core/config.rs`) so both compilation units
// (the library AND `build.rs`) have them in scope via `include!`.
// Keeping them next to the structs also eliminates the previous
// per-field merge-helper pattern that could drift from the schema.

fn default_nim() -> NimConfig {
    NimConfig {
        base_url: default_nim_base_url(),
        embed_model: default_embed_model(),
        rerank_model: String::new(),
        embed_dim_override: None,
        api_key_env: default_api_key_env(),
        batch_size: default_batch_size(),
        request_timeout_secs: default_timeout(),
        retry: RetryConfig::default(),
    }
}

fn default_wiki() -> WikiConfig {
    WikiConfig {
        default_chunk_tokens: default_chunk_tokens(),
        chunk_overlap_tokens: default_chunk_overlap(),
        min_chunk_tokens: default_min_chunk(),
        require_frontmatter: true,
        require_wikilinks_min: default_wikilinks_min(),
    }
}

fn default_nim_base_url() -> String {
    "https://integrate.api.nvidia.com".into()
}

fn default_embed_model() -> String {
    "nvidia/nv-embed-v1".into()
}

fn default_api_key_env() -> String {
    "NVIDIA_NIM_API_KEY".into()
}

fn default_batch_size() -> usize {
    8
}

fn default_timeout() -> u64 {
    30
}

fn default_max_attempts() -> u32 {
    3
}

fn default_backoff() -> u64 {
    500
}

fn default_chunk_tokens() -> usize {
    512
}

fn default_chunk_overlap() -> usize {
    128
}

fn default_min_chunk() -> usize {
    32
}

fn default_wikilinks_min() -> usize {
    2
}

fn default_true() -> bool {
    true
}